-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 19:11:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_rh2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_rh2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_rh2` DEFAULT CHARACTER SET utf8 ;
USE `db_rh2` ;

-- -----------------------------------------------------
-- Table `db_rh2`.`TB_Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh2`.`TB_Departamento` (
  `Id_Departamento` INT NOT NULL AUTO_INCREMENT,
  `DescricaoDepartamento` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_rh2`.`TB_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh2`.`TB_Funcionario` (
  `Id_Funcionario` INT NOT NULL,
  `NomeFuncionario` VARCHAR(45) NULL,
  `EnderecoFuncionario` VARCHAR(100) NULL,
  `TelefoneFuncionario` VARCHAR(11) NULL,
  `DataNascFuncionario` DATE NULL,
  `MatriculaFuncionariocol` INT NULL,
  `TB_Departamento_Id_Departamento` INT NOT NULL,
  PRIMARY KEY (`Id_Funcionario`, `TB_Departamento_Id_Departamento`),
  INDEX `fk_TB_Funcionario_TB_Departamento_idx` (`TB_Departamento_Id_Departamento` ASC) VISIBLE,
  CONSTRAINT `fk_TB_Funcionario_TB_Departamento`
    FOREIGN KEY (`TB_Departamento_Id_Departamento`)
    REFERENCES `db_rh2`.`TB_Departamento` (`Id_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_rh2`.`TB_Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh2`.`TB_Dependentes` (
  `Id_Dependente` INT NOT NULL,
  `NomeDependente` VARCHAR(45) NULL,
  `DataNascimentoDependente` DATE NULL,
  `TB_Funcionario_Id_Funcionario` INT NOT NULL,
  `TB_Funcionario_TB_Departamento_Id_Departamento` INT NOT NULL,
  `SexoDependente` CHAR(1) NULL,
  PRIMARY KEY (`Id_Dependente`),
  INDEX `fk_TB_Dependentes_TB_Funcionario1_idx` (`TB_Funcionario_Id_Funcionario` ASC, `TB_Funcionario_TB_Departamento_Id_Departamento` ASC) VISIBLE,
  CONSTRAINT `fk_TB_Dependentes_TB_Funcionario1`
    FOREIGN KEY (`TB_Funcionario_Id_Funcionario` , `TB_Funcionario_TB_Departamento_Id_Departamento`)
    REFERENCES `db_rh2`.`TB_Funcionario` (`Id_Funcionario` , `TB_Departamento_Id_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;