-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 20:23:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_rh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_rh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_rh` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema db_rh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_rh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_rh` DEFAULT CHARACTER SET utf8 ;
USE `db_rh` ;

-- -----------------------------------------------------
-- Table `db_rh`.`TB - Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh`.`TB - Departamento` (
  `cod_funcionario` VARCHAR(10) NULL,
  `descricao` VARCHAR(45) NULL,
  `dependentes_cod_funcionario` VARCHAR(60) NULL,
  `id_dep` INT NULL,
  PRIMARY KEY (`cod_funcionario`));


-- -----------------------------------------------------
-- Table `db_rh`.`TB - Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh`.`TB - Dependentes` (
  `cod_funcionario` VARCHAR(10) NULL,
  `nome` VARCHAR(45) NULL,
  `codigo` VARCHAR(39) NULL,
  `data_nasc` DATE NULL DEFAULT CURRENT_TIMESTAMP,
  `cod_departamento` VARCHAR(50) NULL,
  `Departamento_cod_funcionario` VARCHAR(10) NOT NULL,
  `sexo_depen` CHAR(1) NULL,
  PRIMARY KEY (`cod_funcionario`),
  INDEX `fk_Dependentes_Departamento1_idx` (`Departamento_cod_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Dependentes_Departamento1`
    FOREIGN KEY (`Departamento_cod_funcionario`)
    REFERENCES `db_rh`.`TB - Departamento` (`cod_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_rh`.`TB - Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh`.`TB - Funcionário` (
  `cod_funcionario` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(9) NULL DEFAULT CURRENT_TIMESTAMP,
  `cod_departamento` VARCHAR(50) NULL,
  `dependentes_cod_funcionario` VARCHAR(60) NULL,
  `Dependentes_cod_funcionario` VARCHAR(10) NOT NULL,
  `data_nasc` DATE NULL,
  `matricula_funcionario` INT NULL,
  `TB - Departamento_id_dep` INT NOT NULL,
  PRIMARY KEY (`cod_funcionario`, `TB - Departamento_id_dep`),
  INDEX `fk_TB - Funcionário_Dependentes_idx` (`Dependentes_cod_funcionario` ASC) VISIBLE,
  INDEX `fk_TB - Funcionário_TB - Departamento1_idx` (`TB - Departamento_id_dep` ASC) VISIBLE,
  CONSTRAINT `fk_TB - Funcionário_Dependentes`
    FOREIGN KEY (`Dependentes_cod_funcionario`)
    REFERENCES `db_rh`.`TB - Dependentes` (`cod_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB - Funcionário_TB - Departamento1`
    FOREIGN KEY (`TB - Departamento_id_dep`)
    REFERENCES `db_rh`.`TB - Departamento` (`cod_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `db_rh` ;

-- -----------------------------------------------------
-- Table `db_rh`.`TB - Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh`.`TB - Departamento` (
  `cod_funcionario` VARCHAR(10) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `dependentes_cod_funcionario` VARCHAR(60) NULL DEFAULT NULL,
  `id_dep` INT NULL DEFAULT NULL,
  PRIMARY KEY (`cod_funcionario`));


-- -----------------------------------------------------
-- Table `db_rh`.`TB - Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh`.`TB - Dependentes` (
  `cod_funcionario` VARCHAR(10) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `codigo` VARCHAR(39) NULL DEFAULT NULL,
  `data_nasc` DATE NULL DEFAULT CURRENT_TIMESTAMP,
  `cod_departamento` VARCHAR(50) NULL DEFAULT NULL,
  `Departamento_cod_funcionario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cod_funcionario`),
  INDEX `fk_Dependentes_Departamento1_idx` (`Departamento_cod_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Dependentes_Departamento1`
    FOREIGN KEY (`Departamento_cod_funcionario`)
    REFERENCES `db_rh`.`TB - Departamento` (`cod_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_rh`.`TB - Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh`.`TB - Funcionário` (
  `cod_funcionario` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(9) NULL DEFAULT CURRENT_TIMESTAMP,
  `cod_departamento` VARCHAR(50) NULL DEFAULT NULL,
  `dependentes_cod_funcionario` VARCHAR(60) NULL DEFAULT NULL,
  `Dependentes_cod_funcionario` VARCHAR(10) NOT NULL,
  `data_nasc` DATE NULL DEFAULT NULL,
  `matricula_funcionario` INT NULL DEFAULT NULL,
  `TB - Departamento_id_dep` INT NOT NULL,
  PRIMARY KEY (`cod_funcionario`, `TB - Departamento_id_dep`),
  INDEX `fk_TB - Funcionário_Dependentes_idx` (`dependentes_cod_funcionario` ASC) VISIBLE,
  INDEX `fk_TB - Funcionário_TB - Departamento1_idx` (`TB - Departamento_id_dep` ASC) VISIBLE,
  CONSTRAINT `fk_TB - Funcionário_Dependentes`
    FOREIGN KEY (`dependentes_cod_funcionario`)
    REFERENCES `db_rh`.`TB - Dependentes` (`cod_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB - Funcionário_TB - Departamento1`
    FOREIGN KEY (`TB - Departamento_id_dep`)
    REFERENCES `db_rh`.`TB - Departamento` (`cod_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;