-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 21:19:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_rh3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_rh3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_rh3` DEFAULT CHARACTER SET utf8 ;
USE `db_rh3` ;

-- -----------------------------------------------------
-- Table `db_rh3`.`tb_exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh3`.`tb_exames` (
  `id_exame` INT NOT NULL,
  `nome_exame` VARCHAR(45) NULL,
  `tipo_exame` VARCHAR(45) NULL,
  PRIMARY KEY (`id_exame`));


-- -----------------------------------------------------
-- Table `db_rh3`.`tb_prontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh3`.`tb_prontuario` (
  `id_prontuario` INT NOT NULL,
  `data_exame` DATETIME NULL,
  `resultado_exame` VARCHAR(200) NULL,
  `status_exame` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tb_prontuariocol` VARCHAR(20) NULL,
  `tb_exames_id_exame` INT NOT NULL,
  PRIMARY KEY (`id_prontuario`, `tb_exames_id_exame`),
  INDEX `fk_tb_prontuario_tb_exames1_idx` (`tb_exames_id_exame` ASC) VISIBLE,
  CONSTRAINT `fk_tb_prontuario_tb_exames1`
    FOREIGN KEY (`tb_exames_id_exame`)
    REFERENCES `db_rh3`.`tb_exames` (`id_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_rh3`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh3`.`tb_clientes` (
  `id_cliente` INT NOT NULL,
  `nome_cliente` VARCHAR(45) NULL,
  `cpf_cliente` VARCHAR(11) NULL,
  `email_cliente` VARCHAR(45) NULL,
  `tb_prontuario_id_prontuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `tb_prontuario_id_prontuario`),
  INDEX `fk_tb_clientes_tb_prontuario_idx` (`tb_prontuario_id_prontuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_clientes_tb_prontuario`
    FOREIGN KEY (`tb_prontuario_id_prontuario`)
    REFERENCES `db_rh3`.`tb_prontuario` (`id_prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_rh3`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rh3`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODECHECKS;
;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_